name: Deploy Zola Site

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zola
        run: |
          curl -s https://get.zola.rs | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
